name: Create Stable Release
on:
  push:
    branches:
      - stable

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Package Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      - name: Create a Stable Release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use_github_release_notes: true
          release_name: "Version ${{ steps.get_flutter_version.outputs.version_number }}"
